
{
  "name": "dutch-number-parser",
  "version": "1.0.0",
  "description": "A TypeScript package to parse and convert Dutch counting numbers into numeric equivalents, supporting numbers up to one million.",
  "main": "dist/index.js",
  "scripts": {
    "build": "tsc",
    "test": "echo \"No tests specified\" && exit 0",
    "prepublishOnly": "npm run build"
  },
  "keywords": [
    "antlr",
    "typescript",
    "dutch",
    "numbers",
    "parser",
    "CC BY-SA 4.0"
  ],
  "author": "Jeroen Bloemscheer",
  "license": "CC-BY-SA-4.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/grootstebozewolf/dutch-number-parser.git"
  },
  "bugs": {
    "url": "https://github.com/grootstebozewolf/dutch-number-parser/issues"
  },
  "homepage": "https://github.com/grootstebozewolf/dutch-number-parser"
}
